### ISSUE TITLE
Why does newest version compiled from source in Linux keep telling me to upgrade my client?

### ISSUE THREAD

**Issue by adrianwebb** [scottdraves/electricsheep#24]
I am running ElectricSheep in Ubuntu 14.04 and everything is compiled and running with the newest libraries and client pulled from this repository (version 2.7b33 according to electricsheep-preferences) but whenever I run it for a while it keeps telling me to upgrade my client.

How do I get ElectricSheep server to recognize that I have the latest version or is the master branch not really the latest version according to the server?

**Comment by scottdraves** [comment]
thanks for the report.
it's actually the server that didn't recognize the latest version.
should be fixed now, let me know if you see otherwise.

**Comment by adrianwebb** [comment]
Thanks a lot!  Will do.
