### ISSUE TITLE
feature request: automatic voting

### ISSUE THREAD

**Issue by aaannndddyyy** [scottdraves/electricsheep#31]
Hi!

I don't know if you have time for this, but I think it would be a nice addition to electronic sheep.

Right now, as I understand it, the only non-random influence to evolution is the user - either by voting or by contributing own sheep.
Problem is, I am not always on my computer, and others are busy too, so I might not even get to see a very nice sheep and thus cannot upvote it. Now chances are high that due to random mutations and simply too many other sheep being around, that this particular niceness dies out.

So why not have an automatic voting system in place, that has an eye on the produced sheep 24/7.
It would run on the user'S device in parallel to the electric sheep.
Yes, that autonomous voter must also have criteria to base its decision on. And it is not human and could be wrong.
But it would also add an interesting layer of complexity to it.
So it could be some neural net work approach with an online learning strategy.
as inputs it receives the current sheep and as an output it yields a single binary output of vote up or no vote at all.
It should not vote down, as it could be wrong, only upvotes.
and its own upvotes should be much less important than a human's upvote.
Like a human's vote counts 1000 or 10000 and the automatic vote only counts 2.

Initially, the vote is random, but whenever the user votes, the NN learns from that user vote.
Its own vote would still be cast (thus representing its outside view of what the user would want), but it's weights updated for the next evaluation, thus representing the user better next time.

Thus the NN gets used to its user's tastes and votes on his behalf in his absence.
For every user there'd be also an automatic voter.

**Comment by Saklad5** [comment]
You aren’t asking for an “automatic voter”. You are asking for a system that builds a profile of the user’s preferences.

The entire point of voting is that it is completely manual. As long as not being voted on doesn’t hurt a sheep, it doesn’t really matter if no one is there to see it.

**Comment by aaannndddyyy** [comment]
Yes, I am asking for a system that builds a sort of profile of the 
user's preferences and then acts accordingly in the votes, i.e. an 
automatic voter.

The point of it, is to get more votes on good sheep, such that even in 
your absence for mthe keyboard, the evolution is driven in a favorable 
direction.
This voter is not meant to replace the human voter, but to represent him 
in his absence.
It can never be a perfect copy of the human, so it will add addtional 
complexity to the process, and also make voting more efficient.
Since it should not cast negative votes, it cannot harm and good sheep 
are not getting lost due to a bad decision of the automatic voting 
system, also the human votes reaim by far more significant - in case 
automatic voter and human disagree: when the human is there to cast his 
vote, the automatic voter's vote is not discarded, but it can still 
vote; however, the human vote has a much higher value / bonus for the 
sheep, maybe higher than 100 automated votes.

**Comment by scottdraves** [comment]
we get plenty of votes to give the genetic algorithm a clear direction.
