### ISSUE TITLE
max_analyze_duration reached

### ISSUE THREAD

**Issue by davidhedlund** [scottdraves/electricsheep#42]
* electricsheep version: 2.7b12
* Graphic driver: NOUVEAU. Gallium 0.4 on NV96

I'm stuck
> $ electricsheep
> [avi @ 0x10a2e60] max_analyze_duration reached
> $ electricsheep --video-driver gl
> [avi @ 0xa8ce60] max_analyze_duration reached

```
lspci | grep VGA ; lsmod | grep "kms\|drm" ; find /dev -group video ; \
> cat /proc/cmdline ; find /etc/modprobe.d/; cat /etc/modprobe.d/*kms* ; \
> ls /etc/X11/xorg.conf ; glxinfo | grep -i "vendor\|rendering" ; \
> grep LoadModule /var/log/Xorg.0.log
04:00.0 VGA compatible controller: NVIDIA Corporation G96 [GeForce 9500 GT] (rev a1)
drm_kms_helper         55071  1 nouveau
drm                   303102  6 ttm,drm_kms_helper,nouveau
/dev/fb0
/dev/dri/card0
/dev/dri/controlD64
BOOT_IMAGE=/boot/vmlinuz-3.13.0-113-lowlatency root=UUID=082c67fc-0312-42cc-be9b-388a34dd3cdf ro quiet splash nomdmonddf nomdmonisw vt.handoff=7
/etc/modprobe.d/
/etc/modprobe.d/openfwwf.conf
/etc/modprobe.d/alsa-base.conf
/etc/modprobe.d/disable-pcsp.conf
/etc/modprobe.d/iwlwifi.conf
/etc/modprobe.d/qemu-system-x86.conf
/etc/modprobe.d/blacklist-ath_pci.conf
/etc/modprobe.d/blacklist-firewire.conf
/etc/modprobe.d/vmwgfx-fbdev.conf
/etc/modprobe.d/blacklist-framebuffer.conf
/etc/modprobe.d/blacklist-oss.conf
/etc/modprobe.d/osspd.conf
/etc/modprobe.d/blacklist.conf
/etc/modprobe.d/blacklist-watchdog.conf
/etc/modprobe.d/fbdev-blacklist.conf
/etc/modprobe.d/disable-radeon.conf
/etc/modprobe.d/mlx4.conf
/etc/modprobe.d/blacklist-modem.conf
/etc/modprobe.d/blacklist-rare-network.conf
cat: /etc/modprobe.d/*kms*: No such file or directory
/etc/X11/xorg.conf
direct rendering: Yes
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
OpenGL vendor string: nouveau
[    20.623] (II) LoadModule: "glx"
[    20.845] (II) LoadModule: "nvidia"
[    20.846] (II) LoadModule: "nouveau"
[    20.847] (II) LoadModule: "modesetting"
[    20.848] (II) LoadModule: "fbdev"
[    20.848] (II) LoadModule: "vesa"
[    20.849] (II) LoadModule: "nvidia"
[    20.849] (II) LoadModule: "nouveau"
[    20.850] (II) LoadModule: "modesetting"
[    20.850] (II) LoadModule: "fbdev"
[    20.850] (II) LoadModule: "vesa"
[    20.852] (II) LoadModule: "fbdevhw"
[    20.852] (II) LoadModule: "dri2"
[    21.014] (II) LoadModule: "fb"
[    21.015] (II) LoadModule: "exa"
[    21.015] (II) LoadModule: "shadowfb"
[    21.131] (II) LoadModule: "evdev"

```

**Comment by scottdraves** [comment]
>  max_analyze_duration reached

this is a harmless warning.  are you getting no display?  what version are you running?

**Comment by davidhedlund** [comment]
@scottdraves 
> are you getting no display?

Exactly.

> what version are you running?

2.7~b12+svn20091224-2build1

**Comment by scottdraves** [comment]
that is ancient, try current src.

**Comment by scottdraves** [comment]
oh i see you mentioned the version in your initial report, sorry i missed it.

**Comment by davidhedlund** [comment]
@scottdraves I don't find an updated PPA for Ubuntu.

**Comment by scottdraves** [comment]
ask Ubuntu about that, i would love it if it were updated.

**Comment by davidhedlund** [comment]
@scottdraves Can you please open this issue again?

> If you have Ubuntu 10.04 or Debian Sid, then you can just use the package manager or type "sudo apt-get install electricsheep", although that will get you an old version, it should work fine. - https://gold.electricsheep.org/linux/

**Comment by scottdraves** [comment]
You are right there is an issue -- but it's just with the website.  I updated that text to not recommend using those versions.

I did find a PPA with a more recent version: https://launchpad.net/~ichthyo/+archive/ubuntu/zeug
it might play free sheep but i don't think it will download Gold.

**Comment by davidhedlund** [comment]
@scottdraves Thank you for directly updating the text.

I actually managed to install el by compiling it myself. It was very easy to do.

**Comment by scottdraves** [comment]
great, glad to hear it.

**Comment by davidhedlund** [comment]
Thanks a lot for providing a reliable PPA! electricsheep works as it should with https://launchpad.net/%7Eichthyo/+archive/ubuntu/zeug, can you add that PPA link to https://gold.electricsheep.org/linux/ ?

**Comment by davidhedlund** [comment]
@scottdraves Oh, you did it already, thanks!
