### ISSUE TITLE
Screensaver not working on Windows 10

### ISSUE THREAD

**Issue by djlauer** [scottdraves/electricsheep#53]
Electric Sheep Screensaver is not working on my system. This is the first time I have downloaded and attempted to run it on this computer:

Dell Inspiron 5520, 64-bit Windows 10
Intel i5-3210M CPU @ 2.50 GHz with 8 GB RAM

I have Electric Sheep version 3.0.
I can run the program in a window (not full screen) from the program settings but the screen saver never kicks in after any period of time. No flickers or error messages that I can find.
Interestingly the program runs just fine on the Mac where I recently installed it.

Thanks for your help.

DJL

**Comment by djlauer** [comment]
I have an update on this perceived problem.
It appears I had VLC open for a few days before and during the time I was trying to get Electric Sheep to run as a screensaver. I recently closed VLC and the screensaver turned on after the appropriate amount of inactivity.

It appears VLC disables the screensaver.

DJL

**Comment by scottdraves** [comment]
cool thanks for following up

BeakerNotebook.com
ScottDraves.com
twitter.com/Scott_Draves
