### ISSUE TITLE
Linux client and gold?

### ISSUE THREAD

**Issue by joshp23** [scottdraves/electricsheep#58]
I installed from master and my client version reads as 2.7b33. Gold requires client version 3 or above. Is there something that I am missing, or are Gold Sheep not available on linux"?

**Comment by scottdraves** [comment]
I think the linux code just hasn't had the version number updated.
There are plenty of folks who are using Linux to run the Gold Sheep.
Did you enter your email and password from the new website into the preferences dialog?

**Comment by joshp23** [comment]
yes i did, I will have to go back and double check everything, but I was certain that I entered it in correctly. It had me as signed in but not Gold, I was on a 2 day trial

**Comment by scottdraves** [comment]
if you email me your account name and hash i can compare to what the server has for you.

**Comment by joshp23** [comment]
It must have had something to do with the trial period? I signed up yesterday and it had me in the trial period, but the charge came through today (?) ... and then it kicked in. The Gold flock is quite nice.

**Comment by scottdraves** [comment]
it waits until the trial period is over before charing your card, but that shouldn't have any impact on your login.  will have to test it some more.  thanks for following up.
