### ISSUE TITLE
Remove 'please upgrade to latest client message'

### ISSUE THREAD

**Issue by guysoft** [scottdraves/electricsheep#69]
Hey, developer of ElectricSheepPi here,
Is there a way to remove this mmessage, which is irrelevant to RaspberryPi users?
![20180529_174412](https://user-images.githubusercontent.com/325670/40666396-45339398-6368-11e8-9758-da8a0484f780.jpg)

Thanks,

**Comment by scottdraves** [comment]
sure what version string is it sending?

**Comment by guysoft** [comment]
What ever is in master here.
It was built yesterday.

Is there a command to return the version?

**Comment by guysoft** [comment]
Where do you set that?

I can see``["os_version"]="LNX_2.7b33"``, in ElectricSheep.cfg

I found the message in ``~/.electricsheep/content/xml/cp_0.xml``
```
<get gen="247" retry="600"><message>please upgrade to the latest client from www.electricsheep.org
</message></get>
```

Output of ~/.electricsheep/ElectricSheep.cfg:
```
return {
-- Table: {1}
{
   ["settings"]={2},
},
-- Table: {2}
{
   ["app"]={3},
   ["player"]={4},
   ["content"]={5},
   ["generator"]={6},
},
-- Table: {3}
{
   ["InstallDir"]="/usr/local/share/electricsheep/",
   ["os_version"]="LNX_2.7b33",
   ["date_time"]="Tue May 29 15:44:28 2018",
   ["log"]=false,
   ["pngfadein"]=10,
   ["attributionpng"]=true,
   ["pnghold"]=10,
   ["pngfadeout"]=10,
},
-- Table: {4}
{
   ["fadecount"]=30,
   ["cpuusagethreshold"]=50,
   ["preserve_AR"]=false,
   ["PlaybackMixingMode"]=0,
   ["hudFontName"]="Trebuchet MS",
   ["screen"]=0,
   ["MultiDisplayMode"]=0,
   ["PlayCountDecayY"]=2000,
   ["display_fps"]="60",
   ["PlayCountDecayZ"]=60,
   ["player_fps"]="20",
   ["PlayEvenly"]=100,
   ["DisplayMode"]=0,
   ["CalculateTransitions"]=true,
   ["SeamlessPlayback"]=false,
   ["reversedisplays"]=false,
   ["LoopIterations"]=2,
   ["BufferLength"]=25,
   ["RandomMedianLevel"]=true,
   ["AutoMedianLevel"]=true,
   ["attrpngfilename"]="/usr/local/share/electricsheep/electricsheep-attr.png",
   ["NormalInterval"]=100,
   ["pngdelaytimer"]=600,
   ["MedianLevel"]=80,
   ["hudFontSize"]=24,
},
-- Table: {5}
{
   ["proxy"]="",
   ["cache_size"]=2000,
   ["sheepdir"]="/home/pi/.electricsheep/content/",
   ["unlimited_cache"]=true,
   ["cache_size_gold"]=2000,
   ["use_proxy"]=false,
   ["redirectserver"]="https://community.sheepserver.net",
   ["password"]="",
   ["download_mode"]=true,
   ["password_md5"]="D41D8CD98F00B204E9800998ECF8427E",
   ["registered"]=false,
   ["unlimited_cache_gold"]=true,
   ["proxy_password"]="",
   ["proxy_username"]="",
   ["unique_id"]="5C3A7209DC65CB36",
},
-- Table: {6}
{
   ["save_frames"]=false,
   ["DelayAfterRenderSeconds"]=1,
   ["nickname"]="",
   ["user_url"]="",
   ["totalFramesRendered"]=0,
   ["enabled"]=true,
   ["all_cores"]=false,
},
}
```

This is what I see in help:
![screenshot_20180530_205113](https://user-images.githubusercontent.com/325670/40738182-867dcab0-644b-11e8-9d7e-b87adab1aac5.png)

**Comment by scottdraves** [comment]
it it in the "nickname":
```
["nickname"]="guysoft_374@gmail.com",
```

**Comment by guysoft** [comment]
Done and rebooted

**Comment by guysoft** [comment]
@scottdraves Been running for 17 hours, any way to test?

**Comment by guysoft** [comment]
Just saw that @Ichthyostega has committed this - perhaps as a workaround?

https://github.com/Ichthyostega/electricsheep/commit/115a32ae008181d601ff563dc93fd04c6944bf2a

**Comment by scottdraves** [comment]
try again, should be good now. the server now allows LNX_2.7b33.
that version string is out of date, it really should LNX_3.0.2, like that commit says,
but that version would also need to be added to the server access list.

**Comment by guysoft** [comment]
Should I make a pull request for the version number?

**Comment by scottdraves** [comment]
Sure that would be great.

Did the "please upgrade" message go away?

**Comment by guysoft** [comment]
I am not next to the machine at the moment, will look when I am there.

BTW - is there a way to increase the resolution rendered?

**Comment by scottdraves** [comment]
For HD you can sign up for the Gold Sheep, the premium version.

**Comment by guysoft** [comment]
Does that work for RaspberryPi?

**Comment by scottdraves** [comment]
i have heard it does but haven't tried it myself. it might depend on which Pi hardware, the old ones might not be powerful enough, idk.

**Comment by guysoft** [comment]
Cool! Running a build for a fixed version ``0.2.1``.
You can follow at: http://gnethomelinux.com:808/job/CustomPiOS/19/console

**Comment by scottdraves** [comment]
i added the new version to the access list as well.

**Comment by guysoft** [comment]
If you want to give me access to test on Premium I can tell you, I have a 3B+ which is the fastest.
If it is, then my distro makes it really easy to use, you just flash it, set up the settings, and its ready to go. I can make it so the ``ElectricSheep.cfg`` is accessible from the ``/boot`` folder.
