### ISSUE TITLE
glee error on ubuntu 18

### ISSUE THREAD

**Issue by nand0p** [scottdraves/electricsheep#77]
/usr/local/include/GL -I/usr/include/GL -I/usr/include/x86_64-linux-gnu -I/usr/include/libpng16 -I/usr/include/lua5.1   -lrt -lz -lGL -D__STDC_CONSTANT_MACROS -Wno-write-strings -DHAVE_AVC_VID2=1 -g -O2   -o electricsheep Player.o main.o Voting.o Hud.o Upload.o Download.o Networking.o LoadDDS.o Image.o RendererGL.o glx.o ShaderGL.o TextureFlatGL.o wgl.o FontGL.o mgl.o Shader.o Texture.o Font.o TextureFlat.o Renderer.o LoadPNG.o DisplayOutput.o tinyxmlparser.o tinyxml.o tinystr.o tinyxmlerror.o diriterator.o storage.o luastorage.o ContentDecoder.o SheepUploader.o ContentDownloader.o SheepGenerator.o SheepDownloader.o Sheep.o Shepherd.o LuaState.o Common.o AlignedBuffer.o isaac.o pool.o Log.o Rect.o luaxml.o Exception.o md5.o -lboost_system -lboost_thread -lboost_filesystem -lglut -lavcodec -lavformat -lswscale -lavutil -llua5.1   -lboost_system -lcurl -lpng16 -lz -lXrender -lX11 -lgtop-2.0 -lglib-2.0 -lXrender -lX11 -lrt -lGL -lglut -ltinyxml -lboost_system -lboost_filesystem -lboost_thread 
libtool: link: g++ -DLINUX_GNU=1 -DSHAREDIR=\"/usr/local/share/electricsheep/\" -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/include/libgtop-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/lua5.1 -I /usr/local/include/GL -I/usr/include/GL -I/usr/include/x86_64-linux-gnu -I/usr/include/libpng16 -I/usr/include/lua5.1 -D__STDC_CONSTANT_MACROS -Wno-write-strings -DHAVE_AVC_VID2=1 -g -O2 -o electricsheep Player.o main.o Voting.o Hud.o Upload.o Download.o Networking.o LoadDDS.o Image.o RendererGL.o glx.o ShaderGL.o TextureFlatGL.o wgl.o FontGL.o mgl.o Shader.o Texture.o Font.o TextureFlat.o Renderer.o LoadPNG.o DisplayOutput.o tinyxmlparser.o tinyxml.o tinystr.o tinyxmlerror.o diriterator.o storage.o luastorage.o ContentDecoder.o SheepUploader.o ContentDownloader.o SheepGenerator.o SheepDownloader.o Sheep.o Shepherd.o LuaState.o Common.o AlignedBuffer.o isaac.o pool.o Log.o Rect.o luaxml.o Exception.o md5.o  -lavcodec -lavformat -lswscale -lavutil -llua5.1 /usr/lib/x86_64-linux-gnu/libcurl.so -lpng16 -lz -lgtop-2.0 -lglib-2.0 -lXrender -lX11 -lrt -lGL -lglut -ltinyxml -lboost_system -lboost_filesystem -lboost_thread -pthread
glx.o: In function `DisplayOutput::CUnixGL::toggleVSync()':
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/glx.cpp:469: undefined reference to `_GLEE_GLX_SGI_swap_control'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/glx.cpp:469: undefined reference to `GLeeEnabled'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/glx.cpp:471: undefined reference to `GLeeFuncPtr_glXSwapIntervalSGI'
ShaderGL.o: In function `DisplayOutput::CShaderGL::Unbind()':
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:82: undefined reference to `GLeeFuncPtr_glUseProgramObjectARB'
ShaderGL.o: In function `DisplayOutput::CShaderGL::~CShaderGL()':
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:41: undefined reference to `GLeeFuncPtr_glDeleteObjectARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:44: undefined reference to `GLeeFuncPtr_glDeleteObjectARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:47: undefined reference to `GLeeFuncPtr_glDeleteObjectARB'
ShaderGL.o: In function `DisplayOutput::CShaderGL::Bind()':
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:55: undefined reference to `GLeeFuncPtr_glUseProgramObjectARB'
ShaderGL.o: In function `DisplayOutput::CShaderUniformGL::Apply()':
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:420: undefined reference to `GLeeFuncPtr_glUniformMatrix4fvARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:417: undefined reference to `GLeeFuncPtr_glUniformMatrix3fvARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:385: undefined reference to `GLeeFuncPtr_glUniform1fvARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:388: undefined reference to `GLeeFuncPtr_glUniform2fvARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:391: undefined reference to `GLeeFuncPtr_glUniform3fvARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:394: undefined reference to `GLeeFuncPtr_glUniform4fvARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:399: undefined reference to `GLeeFuncPtr_glUniform1ivARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:403: undefined reference to `GLeeFuncPtr_glUniform2ivARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:407: undefined reference to `GLeeFuncPtr_glUniform3ivARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:411: undefined reference to `GLeeFuncPtr_glUniform4ivARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:414: undefined reference to `GLeeFuncPtr_glUniformMatrix2fvARB'
ShaderGL.o: In function `DisplayOutput::CShaderGL::Build(char const*, char const*)':
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:100: undefined reference to `_GLEE_ARB_shading_language_100'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:100: undefined reference to `GLeeEnabled'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:128: undefined reference to `GLeeFuncPtr_glCreateProgramObjectARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:133: undefined reference to `GLeeFuncPtr_glCreateShaderObjectARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:136: undefined reference to `GLeeFuncPtr_glShaderSourceARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:137: undefined reference to `GLeeFuncPtr_glCompileShaderARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:138: undefined reference to `GLeeFuncPtr_glGetObjectParameterivARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:140: undefined reference to `GLeeFuncPtr_glAttachObjectARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:144: undefined reference to `GLeeFuncPtr_glGetInfoLogARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:154: undefined reference to `GLeeFuncPtr_glCreateShaderObjectARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:157: undefined reference to `GLeeFuncPtr_glShaderSourceARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:158: undefined reference to `GLeeFuncPtr_glCompileShaderARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:159: undefined reference to `GLeeFuncPtr_glGetObjectParameterivARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:161: undefined reference to `GLeeFuncPtr_glAttachObjectARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:165: undefined reference to `GLeeFuncPtr_glGetInfoLogARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:174: undefined reference to `GLeeFuncPtr_glLinkProgramARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:175: undefined reference to `GLeeFuncPtr_glGetObjectParameterivARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:176: undefined reference to `GLeeFuncPtr_glGetInfoLogARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:184: undefined reference to `GLeeFuncPtr_glUseProgramObjectARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:187: undefined reference to `GLeeFuncPtr_glGetObjectParameterivARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:188: undefined reference to `GLeeFuncPtr_glGetObjectParameterivARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:198: undefined reference to `GLeeFuncPtr_glGetActiveUniformARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:203: undefined reference to `GLeeFuncPtr_glGetUniformLocationARB'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:209: undefined reference to `GLeeFuncPtr_glUniform1i'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:291: undefined reference to `GLeeFuncPtr_glUseProgram'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/ShaderGL.cpp:255: undefined reference to `GLeeFuncPtr_glGetUniformLocationARB'
TextureFlatGL.o: In function `DisplayOutput::CTextureFlatGL::Upload(Base::CRefCountPtr<DisplayOutput::CImage, Base::CRefCountRep<DisplayOutput::CImage>, DisplayOutput::CImage*>)':
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/TextureFlatGL.cpp:215: undefined reference to `_GLEE_ARB_texture_non_power_of_two'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/TextureFlatGL.cpp:215: undefined reference to `GLeeEnabled'
/home/nando/repos/electricsheep/client_generic/Client/../DisplayOutput/OpenGL/TextureFlatGL.cpp:186: undefined reference to `GLeeFuncPtr_glCompressedTexImage2DARB'
collect2: error: ld returned 1 exit status
Makefile:539: recipe for target 'electricsheep' failed
make[1]: *** [electricsheep] Error 1
make[1]: Leaving directory '/home/nando/repos/electricsheep/client_generic/Client'
Makefile:513: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by stefantalpalaru** [comment]
Install the "glee-dev" package.
